import React, {useState} from 'react';
import './style.css'; 
import imgRegion from'../Southern region of Brazil.png'
import pr from'../State of Parana.png'
import sc from'../State of Santa Catarina.png'
import rs from'../State of Rio Grande do Sul.png'

function MenuBar() {

  const [region, setRegion] = useState('desc');

  const changeScreen = (operacao) => {
    switch (operacao) {
      case 'region':
        setRegion('region');
        break;
      case 'pr':
        setRegion('pr');
        break;
      case 'sc':
        setRegion('sc');
        break;
      case 'rs':
        setRegion('rs');
        break;
      case 'desc':
        setRegion('desc');
         break;
      default:
        break;
    }
  };


  return (
    <>
    <div className="menu-bar">
      <ul>
        <li onClick={()=>changeScreen('desc')}><p>Description</p></li>
        <li onClick={()=>changeScreen('region')}><p>South Region Brazil</p></li>
        <li onClick={()=>changeScreen('pr')}><p>Paraná</p></li>
        <li onClick={()=>changeScreen('sc')}><p>Santa Catarina</p></li>
        <li onClick={()=>changeScreen('rs')}><p>Rio Grande do Sul</p></li>
        
      </ul>
    </div>

    <div style={region === "desc"?
    {
    width: "70%",
    margin: "0 auto",
    textAlign: "justify",
    paddingTop: "50px",
    }
    :{display:'none'}}>  
    <b>We acquired our dataset from the reputable source <a target="_blanck" href={"http://labren.ccst.inpe.br/atlas_2017.html"}>http://labren.ccst.inpe.br/atlas_2017.html</a>, a valuable resource for gathering data related to energy and environmental factors. This dataset formed the foundation for our geographical analysis, which aimed to shed light on the solar irradiation patterns across the southern Brazilian region, specifically focusing on the states of Paraná, Santa Catarina, and Rio Grande do Sul.

To carry out this study effectively, we initiated the process by dividing the dataset among the aforementioned Brazilian states. This division allowed us to isolate and concentrate our analysis on these specific regions. Furthermore, we combined the datasets from these states to construct a comprehensive representation of the entire southern Brazilian region.

Our data manipulation and analysis were executed using Python, a versatile programming language known for its data science capabilities. We harnessed the power of the Python Pandas library, utilizing its "buildSubset" function to extract the relevant information for our study. This function helped us filter and organize the data, ensuring that we had precise and isolated datasets for each of the targeted states.

One of the key aspects of our analysis was the application of the K-means clustering algorithm. This machine learning algorithm played a pivotal role in segmenting the mapped data into five distinct clusters, or center points. These clusters were instrumental in dividing the region into equivalent zones, each characterized by its solar irradiation characteristics. This segmentation allowed us to gain a deeper understanding of how solar irradiation varies across the southern Brazilian region.

In order to visualize our findings and present them in a comprehensible manner, we turned to the Matplotlib library. This powerful Python library enabled us to create visually appealing and informative graphics using the subsets of data generated by the Python "buildSubset" function. Through these visual representations, we aimed to convey the spatial distribution of solar irradiation in the southern Brazilian region clearly.

Lastly, our color-coded graphics featured a gradient that effectively conveyed the fluctuations in horizontal global irradiation indices throughout the year 2017. This color gradient provided a visual representation of areas where the highest and lowest solar irradiation levels were recorded. This information is vital for understanding the solar energy potential of different regions within southern Brazil and can be a valuable resource for energy planning and environmental analysis.

In summary, our study was a data-driven exploration of solar irradiation patterns in the southern Brazilian region. Leveraging advanced data analysis techniques, machine learning algorithms, and data visualization tools, we aimed to provide valuable insights into the solar energy landscape of this region, which can inform sustainable energy policies and environmental decisions.</b>

    </div>



    <div style={region === "region"?{}:{display:'none'}}><img className="imgGrafic" src={imgRegion} alt="" /></div>
    <div style={region === "pr"?{}:{display:'none'}}><img className="imgGrafic" src={pr} alt="" /></div>
    <div style={region === "sc"?{}:{display:'none'}}><img className="imgGrafic" src={sc} alt="" /></div>
    <div style={region === "rs"?{}:{display:'none'}}><img className="imgGrafic" src={rs} alt="" /></div>
    </>
  );
}

export default MenuBar;
